# gitHub Action name
name: build-images

# execute timing / branches
on:
  push:
    branches:
      - master

# jobs
jobs:

  # build-images
  build-images:
    runs-on: ubuntu-latest
    steps:
      # 拉取指定分支源码（actions/checkout@master库）
      - name: checkout
        uses: actions/checkout@master

        # build images 此处会找当前目录下的Dockerfile构建镜像
      - name: build  images
        run:  docker build -t frontend:latest .

        # 登陆阿里云镜像容器服务
      - name: login aliyun
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} ${{secrets.DOCKER_REGISTRY}} --password=${{ secrets.DOCKER_PASSWORD }}

        # 打版本
      - name: tag
        run: docker tag frontend ${{secrets.DOCKER_REGISTRY}}/homepage-frontend/frontend:latest

        # push docker images
      - name: push docker images
        run: docker push ${{secrets.DOCKER_REGISTRY}}/homepage-frontend/frontend:latest
