# GitHub Action Name
name: build docker images

# Execute Timing & Appoint Branch
on:
  push:
    branches:
      - master

# Jobs
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t fronted:latest -f /Dockerfile .
      - run: docker login --username=${{ secrets.DOCKER_USERNAME }} ${{secrets.DOCKER_REGISTRY}} --password=${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag frontend ${{secrets.DOCKER_REGISTRY}}/homepage-frontend/frontend:latest
      - run: docker push ${{secrets.DOCKER_REGISTRY}}/homepage-frontend/frontend:latest