# gitHub Action name
name: deploy front-end

# execute timing / branches
on:
  push:
    branches:
      - master

# jobs
jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
        # 拉取指定分支源码（actions/checkout@master库）
      - name: checkout
        uses: actions/checkout@master

        # node环境构建（actions/setup-node@v3库）
      - name: install node
        uses: actions/setup-node@v3

        # package.json依赖安装
      - name: dependencies install
        run: npm install

        # 打包构建
      - name: project build
        run: npm run build --if-present

        # build images
      - name: build  images
        run:  docker build -t frontend:latest .

        # 登陆阿里云镜像容器服务()
        # Cannot perform an interactive login from a non TTY device 报错需要添加 winpty
      - name: login aliyun
        run: winpty docker login --username=${{ secrets.DOCKER_USERNAME }} {{secrets.DOCKER_REGISTRY}} --password=${{ secrets.DOCKER_PASSWORD }}
          
        # 打版本
#      - name: tag
#        run: docker tag frontend {{secrets.DOCKER_DOCKER_REGISTRY}}/homepage-frontend/frontend:latest

        # push docker images
      - name: push docker images
        run: docker push {{secrets.DOCKER_DOCKER_REGISTRY}}/homepage-frontend/frontend:latest

        # 登陆云服务器拉取打包好的镜像
  deploy:
    needs: [build]
    name: pull docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
#          script: cd /home/react-demo/ && sh react-demo.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
