# gitHub Action name
name: push-code

# execute timing / branches
on:
  push:
    branches:
      - develop

# jobs
jobs:

  # npm build
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取指定分支源码（actions/checkout@master库）
      - name: checkout
        uses: actions/checkout@master

        # node环境构建（actions/setup-node@v3库）
      - name: install node
        uses: actions/setup-node@v3

        # package.json依赖安装
      - name: dependencies install & build
        run: |
          npm install
          npm run build --if-present
        env:
         CI: false

        # build文件copy至nginx/html文件夹
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
         ARGS: "-rltgoDzvO --delete"
         SOURCE: "build/"
         REMOTE_HOST: ${{ secrets.SSH_HOST }}
         REMOTE_USER: ${{ secrets.SSH_USERNAME }}
         TARGET: ${{ secrets.SSH_TARGET }}
         EXCLUDE: "/build/, /node_modules/"
