# gitHub Action name
name: deploy front-end

# execute timing / branches
on:
  pull_request:
    branches:
      - master

# jobs
jobs:

  # npm build
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取指定分支源码（actions/checkout@master库）
      - name: checkout
        uses: actions/checkout@master

        # node环境构建（actions/setup-node@v3库）
      - name: install node
        uses: actions/setup-node@v3

        # package.json依赖安装
      - name: dependencies install
        run: npm install

        # 打包构建
      - name: project build
        run: npm run build --if-present

  # ssh Tecent ECS docker pull and run images for deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # 登陆云服务器拉取打包好的镜像
      - name: ssh put build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo -e "---------SSH登录腾讯云服务器--------"
            echo -e "---------文件上传完毕--------"
