# gitHub Action name
name: push-code

# execute timing / branches
on:
  push:
    branches:
      - develop

# jobs
jobs:

  # npm build
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取指定分支源码（actions/checkout@master库）
      - name: checkout
        uses: actions/checkout@master

        # node环境构建（actions/setup-node@v3库）
      - name: install node
        uses: actions/setup-node@v3

        # package.json依赖安装
      - name: dependencies install & build
        run: |
          npm install
          npm run build --if-present

        # 登陆云服务器拉取打包好的镜像
      - name: SCP build files
        uses: siva1024/scp-deployer@latest
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         source: "build"
         target: "~/data/nginx/html"
         script: |
            echo -e "---------SSH登录腾讯云服务器--------"
            echo -e "---------文件上传完毕--------"
